# Generated by Django 4.1 on 2022-08-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_imageitem_alter_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="image",
            new_name="item_image",
        ),
    ]
