# Generated by Django 4.1 on 2022-08-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("store", "0002_remove_address_user_remove_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ref_code",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
    ]
