# Generated by Django 4.1 on 2022-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
