# Generated by Django 4.1 on 2022-08-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="device",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
